version: "3.1"

services:

  prismadb:
    restart: always
    image: postgres
    container_name: prismadb #you can change this
    environment:
      - POSTGRES_USER=demo
      - POSTGRES_PASSWORD=demo
      - POSTGRES_DB=demo
      - POSTGRES_PORT=8791
    ports:
      - "8791:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data2/

  prismasdb:
    restart: always
    image: postgres
    container_name: prismasdb #you can change this
    environment:
      - POSTGRES_USER=demo
      - POSTGRES_PASSWORD=demo
      - POSTGRES_DB=demo
      - POSTGRES_PORT=8792
    ports:
      - "8792:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data3/


volumes:
  postgres_data: